site_name: 2020_5EI_Team1
nav:
    - 'Project Charter': 'Project_Charter.md'
    - 'Software Requirements Specification': 'SoftwareRequirementsSpecification.md'
    - 'Software Project Management Plan': 'Software_Project_Management_Plan.md'
    - 'Test Plan': 'Test_Plan.md'
    - 'Iteration Plan': 'Iteration_Plan.md'
    
theme:
    name: readthedocs

use_directory_urls: true
